onos-config:
#  openidc:
#    issuer: https://dex.aetherproject.org/dex
#  plugin:
#    compiler:
#      target: "github.com/sbconsulting/onos-config@diags"
  image:
    tag: v0.10.4
#    repository: docker.smbaker.dev/onos-config
#    tag: smbaker
#    pullPolicy: Always

#onos-topo:
#  image:
#    repository: docker.smbaker.dev/onos-topo
#    tag: smbaker
#    pullPolicy: Always

#onos-sdran-cli:
#  image:
#    repository: onosproject/onos-sdran-cli
#    tag: v0.7.0

#global:
#  storage:
#    controller: "atomix-controller.micro-onos.svc.cluster.local:5679"

import:
  sdcore-adapter:
    enabled: true
  onos-gui:
    enabled: true

x-sdcore-adapter-v4:
  partialUpdateEnabled: true
  prometheusEnabled: false
  image:
    repository: docker.smbaker.dev/sdcore-adapter
    tag: smbaker
    pullPolicy: Always

sdcore-adapter-v2:
  partialUpdateEnabled: true
  prometheusEnabled: false
  image:
    repository: docker.smbaker.dev/sdcore-adapter
    tag: smbaker
    pullPolicy: Always

x-sdcore-exporter:
  prometheusEnabled: false
  image:
    repository: docker.smbaker.dev/sdcore-adapter
    tag: smbaker
    pullPolicy: Always

onos-exporter:
  prometheusEnabled: false

onos-gui:
  ingress:
    enabled: false
  service:
    type: NodePort

aether-roc-gui-v21:
  ingress:
    enabled: false
  service:
    type: NodePort
#  openidc:
#        issuer: https://dex.aetherproject.org/dex
#  image:
#     repository: smbaker/aether-roc-gui
#     tag: smbaker
#     pullPolicy: Always

aether-roc-gui:
  ingress:
    enabled: false
  service:
    type: NodePort
#  openidc:
#        issuer: https://dex.aetherproject.org/dex

aether-roc-api:
   image:
     repository: docker.smbaker.dev/aether-roc-api
     websocketsidecar:
         repository: docker.smbaker.dev/aether-roc-websocket
     tag: smbaker
     pullPolicy: Always
#   corsOrigins:
#   - https://editor.swagger.io

not-prometheus:
  serverFiles:
    prometheus.yml:
      scrape_configs:
      # default scrape interval is 1m

      # scrape thyself
      - job_name: prometheus
        scrape_interval: 5m
        static_configs:
          - targets: ['sdcore-exporter:2112']

grafana:
  adminUser: admin
  adminPassword: myadminpassword
  grafana.ini:
    auth.generic_oauth:
      enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://aether-roc-umbrella-prometheus-server/
          access: proxy
          isDefault: true
