#!/bin/bash

SCRIPTDIR=$(dirname $0)
source $SCRIPTDIR/env.sh

WHAT=$1
FN=$2
if [ ! -f "$FN" ]; then
    echo "$FN does not exist. Trying $AETHER_REST/$FN"
    FN=$AETHER_REST/$FN
fi
if [ ! -f "$FN" ]; then
    echo "$FN does not exist"
    exit
fi
STUFF=`cat $FN`

URL="$AETHER_ROC_API_URL/aether/v1.0.0/$SDCORE_TARGET/$WHAT"
curl --location --request POST $URL \
    --header 'Content-Type: application/json' \
    --data "$STUFF"
